on:
  workflow_dispatch:
    inputs:
      version:
        description: "Netbeans version"
        required: true

jobs:
  package_netbeans:
    name: Package Netbeans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dh-make
        run: sudo apt-get update && sudo apt-get install -y dh-make devscripts build-essential
      - name: Make script executable
        run: chmod +x ./package.sh
      - name: Run the script
        run: ./package.sh ${{ github.event.inputs.version }}
      - name: Upload Debian package
        uses: actions/upload-artifact@v3
        with:
          name: apache-netbeans-deb
          path: ../*.deb
