on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Netbeans version'
        required: true

jobs:
  package_netbeans:
    name: Package Netbeans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Make script executable
        run: chmod +x ./package.sh
      - name: Run the script
        run: ./package.sh
